import { useEffect, useRef } from 'react';
import { createClient } from '@supabase/supabase-js';

/**
 * useSupabaseRealtime Hook
 * 
 * Provides a clean abstraction for listening to PostgreSQL changes.
 * Bypasses Laravel Echo for more direct, low-latency database signals.
 * 
 * @param {string} url - Supabase project URL
 * @param {string} anonKey - Supabase anonymous key
 * @param {string} token - Secure JWT generated by Laravel for auth
 * @param {string} tenantId - The tenant ID to filter events
 * @param {Object} options - Configuration for table and callback
 */
export const useSupabaseRealtime = (url, anonKey, token, tenantId, { table, event = 'INSERT', onPayload }) => {
    const supabaseRef = useRef(null);

    useEffect(() => {
        if (!url || !anonKey || !token || !tenantId) return;

        // 1. Initialize Client
        if (!supabaseRef.current) {
            supabaseRef.current = createClient(url, anonKey);
        }

        const supabase = supabaseRef.current;

        // 2. Set Auth Token
        supabase.realtime.setAuth(token);

        // 3. Initialize Channel
        const channel = supabase
            .channel(`realtime:${table}:${tenantId}`)
            .on(
                'postgres_changes',
                {
                    event,
                    schema: 'public',
                    table,
                    filter: `tenant_id=eq.${tenantId}`,
                },
                (payload) => {
                    if (onPayload) onPayload(payload);
                }
            )
            .subscribe((status) => {
                // Subscription active
            });

        // 4. Cleanup
        return () => {
            supabase.removeChannel(channel);
        };
    }, [url, anonKey, token, tenantId, table, event, onPayload]);

    return supabaseRef.current;
};
